use super::cpu::AddressingMode;

#[derive(Debug)]
pub(crate) struct Instruction {
    #[allow(unused)]
    pub opcode: u8,
    #[allow(unused)]
    pub mnemonic: &'static str,
    pub cycles: usize,
    pub bytes: usize,
    pub mode: AddressingMode,
}

pub(crate) static INSTRUCTIONS: [Instruction; 256] = [
    Instruction {
        opcode: 0x00,
        mnemonic: "BRK",
        cycles: 7,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x01,
        mnemonic: "ORA",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x02,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x03,
        mnemonic: "SLO",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x04,
        mnemonic: "NOP",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x05,
        mnemonic: "ORA",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x06,
        mnemonic: "ASL",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x07,
        mnemonic: "SLO",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x08,
        mnemonic: "PHP",
        cycles: 3,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x09,
        mnemonic: "ORA",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x0A,
        mnemonic: "ASL",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x0B,
        mnemonic: "ANC",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x0C,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x0D,
        mnemonic: "ORA",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x0E,
        mnemonic: "ASL",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x0F,
        mnemonic: "SLO",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x10,
        mnemonic: "BPL",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Relative,
    },
    Instruction {
        opcode: 0x11,
        mnemonic: "ORA",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x12,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x13,
        mnemonic: "SLO",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x14,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x15,
        mnemonic: "ORA",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x16,
        mnemonic: "ASL",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x17,
        mnemonic: "SLO",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x18,
        mnemonic: "CLC",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x19,
        mnemonic: "ORA",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x1A,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x1B,
        mnemonic: "SLO",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x1C,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x1D,
        mnemonic: "ORA",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x1E,
        mnemonic: "ASL",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x1F,
        mnemonic: "SLO",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x20,
        mnemonic: "JSR",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x21,
        mnemonic: "AND",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x22,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x23,
        mnemonic: "RLA",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x24,
        mnemonic: "BIT",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x25,
        mnemonic: "AND",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x26,
        mnemonic: "ROL",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x27,
        mnemonic: "RLA",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x28,
        mnemonic: "PLP",
        cycles: 4,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x29,
        mnemonic: "AND",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x2A,
        mnemonic: "ROL",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x2B,
        mnemonic: "ANC",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x2C,
        mnemonic: "BIT",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x2D,
        mnemonic: "AND",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x2E,
        mnemonic: "ROL",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x2F,
        mnemonic: "RLA",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x30,
        mnemonic: "BMI",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Relative,
    },
    Instruction {
        opcode: 0x31,
        mnemonic: "AND",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x32,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x33,
        mnemonic: "RLA",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x34,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x35,
        mnemonic: "AND",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x36,
        mnemonic: "ROL",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x37,
        mnemonic: "RLA",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x38,
        mnemonic: "SEC",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x39,
        mnemonic: "AND",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x3A,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x3B,
        mnemonic: "RLA",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x3C,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x3D,
        mnemonic: "AND",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x3E,
        mnemonic: "ROL",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x3F,
        mnemonic: "RLA",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x40,
        mnemonic: "RTI",
        cycles: 6,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x41,
        mnemonic: "EOR",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x42,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x43,
        mnemonic: "SRE",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x44,
        mnemonic: "NOP",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x45,
        mnemonic: "EOR",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x46,
        mnemonic: "LSR",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x47,
        mnemonic: "SRE",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x48,
        mnemonic: "PHA",
        cycles: 3,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x49,
        mnemonic: "EOR",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x4A,
        mnemonic: "LSR",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x4B,
        mnemonic: "ALR",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x4C,
        mnemonic: "JMP",
        cycles: 3,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x4D,
        mnemonic: "EOR",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x4E,
        mnemonic: "LSR",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x4F,
        mnemonic: "SRE",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x50,
        mnemonic: "BVC",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Relative,
    },
    Instruction {
        opcode: 0x51,
        mnemonic: "EOR",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x52,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x53,
        mnemonic: "SRE",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x54,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x55,
        mnemonic: "EOR",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x56,
        mnemonic: "LSR",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x57,
        mnemonic: "SRE",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x58,
        mnemonic: "CLI",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x59,
        mnemonic: "EOR",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x5A,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x5B,
        mnemonic: "SRE",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x5C,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x5D,
        mnemonic: "EOR",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x5E,
        mnemonic: "LSR",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x5F,
        mnemonic: "SRE",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x60,
        mnemonic: "RTS",
        cycles: 6,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x61,
        mnemonic: "ADC",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x62,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x63,
        mnemonic: "RRA",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x64,
        mnemonic: "NOP",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x65,
        mnemonic: "ADC",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x66,
        mnemonic: "ROR",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x67,
        mnemonic: "RRA",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x68,
        mnemonic: "PLA",
        cycles: 4,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x69,
        mnemonic: "ADC",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x6A,
        mnemonic: "ROR",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x6B,
        mnemonic: "ARR",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x6C,
        mnemonic: "JMP",
        cycles: 5,
        bytes: 3,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x6D,
        mnemonic: "ADC",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x6E,
        mnemonic: "ROR",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x6F,
        mnemonic: "RRA",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x70,
        mnemonic: "BVS",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Relative,
    },
    Instruction {
        opcode: 0x71,
        mnemonic: "ADC",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x72,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x73,
        mnemonic: "RRA",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x74,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x75,
        mnemonic: "ADC",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x76,
        mnemonic: "ROR",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x77,
        mnemonic: "RRA",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x78,
        mnemonic: "SEI",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x79,
        mnemonic: "ADC",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x7A,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x7B,
        mnemonic: "RRA",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x7C,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x7D,
        mnemonic: "ADC",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x7E,
        mnemonic: "ROR",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x7F,
        mnemonic: "RRA",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x80,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x81,
        mnemonic: "STA",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x82,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x83,
        mnemonic: "SAX",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0x84,
        mnemonic: "STY",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x85,
        mnemonic: "STA",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x86,
        mnemonic: "STX",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x87,
        mnemonic: "SAX",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0x88,
        mnemonic: "DEY",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x89,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x8A,
        mnemonic: "TXA",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x8B,
        mnemonic: "XAA",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0x8C,
        mnemonic: "STY",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x8D,
        mnemonic: "STA",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x8E,
        mnemonic: "STX",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x8F,
        mnemonic: "SAX",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0x90,
        mnemonic: "BCC",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Relative,
    },
    Instruction {
        opcode: 0x91,
        mnemonic: "STA",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x92,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x93,
        mnemonic: "AHX",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0x94,
        mnemonic: "STY",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x95,
        mnemonic: "STA",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0x96,
        mnemonic: "STX",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageY,
    },
    Instruction {
        opcode: 0x97,
        mnemonic: "SAX",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageY,
    },
    Instruction {
        opcode: 0x98,
        mnemonic: "TYA",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x99,
        mnemonic: "STA",
        cycles: 5,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x9A,
        mnemonic: "TXS",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0x9B,
        mnemonic: "TAS",
        cycles: 5,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x9C,
        mnemonic: "SHY",
        cycles: 5,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x9D,
        mnemonic: "STA",
        cycles: 5,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0x9E,
        mnemonic: "SHX",
        cycles: 5,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0x9F,
        mnemonic: "AHX",
        cycles: 5,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xA0,
        mnemonic: "LDY",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xA1,
        mnemonic: "LDA",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0xA2,
        mnemonic: "LDX",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xA3,
        mnemonic: "LAX",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0xA4,
        mnemonic: "LDY",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xA5,
        mnemonic: "LDA",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xA6,
        mnemonic: "LDX",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xA7,
        mnemonic: "LAX",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xA8,
        mnemonic: "TAY",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xA9,
        mnemonic: "LDA",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xAA,
        mnemonic: "TAX",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xAB,
        mnemonic: "LAX",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xAC,
        mnemonic: "LDY",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xAD,
        mnemonic: "LDA",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xAE,
        mnemonic: "LDX",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xAF,
        mnemonic: "LAX",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xB0,
        mnemonic: "BCS",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Relative,
    },
    Instruction {
        opcode: 0xB1,
        mnemonic: "LDA",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0xB2,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xB3,
        mnemonic: "LAX",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0xB4,
        mnemonic: "LDY",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xB5,
        mnemonic: "LDA",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xB6,
        mnemonic: "LDX",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageY,
    },
    Instruction {
        opcode: 0xB7,
        mnemonic: "LAX",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageY,
    },
    Instruction {
        opcode: 0xB8,
        mnemonic: "CLV",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xB9,
        mnemonic: "LDA",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xBA,
        mnemonic: "TSX",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xBB,
        mnemonic: "LAS",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xBC,
        mnemonic: "LDY",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xBD,
        mnemonic: "LDA",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xBE,
        mnemonic: "LDX",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xBF,
        mnemonic: "LAX",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xC0,
        mnemonic: "CPY",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xC1,
        mnemonic: "CMP",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0xC2,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xC3,
        mnemonic: "DCP",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0xC4,
        mnemonic: "CPY",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xC5,
        mnemonic: "CMP",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xC6,
        mnemonic: "DEC",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xC7,
        mnemonic: "DCP",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xC8,
        mnemonic: "INY",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xC9,
        mnemonic: "CMP",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xCA,
        mnemonic: "DEX",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xCB,
        mnemonic: "AXS",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xCC,
        mnemonic: "CPY",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xCD,
        mnemonic: "CMP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xCE,
        mnemonic: "DEC",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xCF,
        mnemonic: "DCP",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xD0,
        mnemonic: "BNE",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Relative,
    },
    Instruction {
        opcode: 0xD1,
        mnemonic: "CMP",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0xD2,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xD3,
        mnemonic: "DCP",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0xD4,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xD5,
        mnemonic: "CMP",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xD6,
        mnemonic: "DEC",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xD7,
        mnemonic: "DCP",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xD8,
        mnemonic: "CLD",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xD9,
        mnemonic: "CMP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xDA,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xDB,
        mnemonic: "DCP",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xDC,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xDD,
        mnemonic: "CMP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xDE,
        mnemonic: "DEC",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xDF,
        mnemonic: "DCP",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xE0,
        mnemonic: "CPX",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xE1,
        mnemonic: "SBC",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0xE2,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xE3,
        mnemonic: "ISC",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectX,
    },
    Instruction {
        opcode: 0xE4,
        mnemonic: "CPX",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xE5,
        mnemonic: "SBC",
        cycles: 3,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xE6,
        mnemonic: "INC",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xE7,
        mnemonic: "ISC",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::ZeroPage,
    },
    Instruction {
        opcode: 0xE8,
        mnemonic: "INX",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xE9,
        mnemonic: "SBC",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xEA,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xEB,
        mnemonic: "SBC",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Immediate,
    },
    Instruction {
        opcode: 0xEC,
        mnemonic: "CPX",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xED,
        mnemonic: "SBC",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xEE,
        mnemonic: "INC",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xEF,
        mnemonic: "ISC",
        cycles: 6,
        bytes: 3,
        mode: AddressingMode::Absolute,
    },
    Instruction {
        opcode: 0xF0,
        mnemonic: "BEQ",
        cycles: 2,
        bytes: 2,
        mode: AddressingMode::Relative,
    },
    Instruction {
        opcode: 0xF1,
        mnemonic: "SBC",
        cycles: 5,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0xF2,
        mnemonic: "JAM",
        cycles: 0,
        bytes: 0,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xF3,
        mnemonic: "ISC",
        cycles: 8,
        bytes: 2,
        mode: AddressingMode::IndirectY,
    },
    Instruction {
        opcode: 0xF4,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xF5,
        mnemonic: "SBC",
        cycles: 4,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xF6,
        mnemonic: "INC",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xF7,
        mnemonic: "ISC",
        cycles: 6,
        bytes: 2,
        mode: AddressingMode::ZeroPageX,
    },
    Instruction {
        opcode: 0xF8,
        mnemonic: "SED",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xF9,
        mnemonic: "SBC",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xFA,
        mnemonic: "NOP",
        cycles: 2,
        bytes: 1,
        mode: AddressingMode::None,
    },
    Instruction {
        opcode: 0xFB,
        mnemonic: "ISC",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteY,
    },
    Instruction {
        opcode: 0xFC,
        mnemonic: "NOP",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xFD,
        mnemonic: "SBC",
        cycles: 4,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xFE,
        mnemonic: "INC",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
    Instruction {
        opcode: 0xFF,
        mnemonic: "ISC",
        cycles: 7,
        bytes: 3,
        mode: AddressingMode::AbsoluteX,
    },
];
